### ISSUE TITLE
HEX not working

### ISSUE THREAD

**Issue by DarkKeeper1** [PaperMC/Velocity#872] opened 2022-09-20 11:59 UTC
Greetings, dear Velocity developers, I am writing with a complaint that I want to make the entire server in 1 style with HEX, which does not work for you in the messages.properties file, either the usual color is displayed instead or nothing is displayed, please do so was HEX and I was able to do it with methods like on the site https://rgb.birdflop.com/, thanks in advance, I hope you will do it.

**Comment by 4drian3d** [comment] 2022-09-20 14:40
Duplicate of https://github.com/PaperMC/Velocity/issues/720

**Closed as completed** 2022-12-12 04:30 UTC
Labels: resolution: duplicate
