### ISSUE TITLE
Refresh bug

### ISSUE THREAD

**Issue by Pierrot-la-menace** [PaperMC/Velocity#630] opened 2022-01-14 17:05 UTC
**Server version**
Velocity 3.1.2 - Paper 1.18.1 build 147

**Describe the bug**
The bar display doesn't refresh when the player just logged in the server. The ping stays at -1 in the beginning of the connection during 2-3 seconds (it's normal) and when it is rightly computed, the bars stay crossed.

**How to reproduce**
Restart your infra, connect 2 players and display the tab list

**Expected behavior**
The bars must be green

**Actual behavior**
The bars are red crossed

**Additional info (errors, screenshots, ...)**
![image](https://user-images.githubusercontent.com/45047908/149555575-f61eacfe-b44d-4c20-9a8f-e37da71681cd.png)

**Comment by KoxSosen** [comment] 2022-01-14 17:32
I'm unable to reproduce this on `Velocity 3.1.2-SNAPSHOT (git-b8f1df44-b110)`, and `git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)` .

Could you please try to reproduce this without any plugins? Regardless, this seems like either a network issue, or the tab plugin delaying the display of the ping bar to me.

**Comment by Pierrot-la-menace** [comment] 2022-01-14 17:39
I already asked to the plugin editor, they answered me that the plugin doesn't touch to the ping bar and the ping value.
I will try to reproduce the bug as you suggest ;)

**Comment by astei** [comment] 2022-03-09 07:28
Closing due to staleness plus this is a suspected plugin issue.

**Closed as completed by astei** 2022-03-09 07:28 UTC
