### ISSUE TITLE
error in connect with 1.8.9

### ISSUE THREAD

**Issue by 0ZyroX** [PaperMC/Velocity#1300] opened 2024-04-23 18:29 UTC
```[22:56:47 ERROR]: [connected player] NoBody (/87.251.148.234:13261): unable to connect to server auth
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
[22:56:47 INFO]: [connected player] NoBody (/87.251.148.234:13261) has disconnected: Unable to connect you to auth. Please try again later.```

**Comment by electronicboy** [comment] 2024-04-23 18:31
This is not the place for support, you would need to work out why the backend server closed the connection

**Comment by Luccboy** [comment] 2024-04-23 18:32
Duplicate of https://github.com/PaperMC/Velocity/issues/1293

**Closed as not planned by electronicboy** 2024-04-23 18:31 UTC
