### ISSUE TITLE
MOTD behavior

### ISSUE THREAD

**Issue by wiktor-jozwiak** [PaperMC/Velocity#769] opened 2022-06-22 13:46 UTC
After setting the MOTD in velocity.toml and after shutting down the server, the MOTD from velocity changes to a motd like the one in the image when shutting it down.
![image](https://user-images.githubusercontent.com/61411400/175044485-a3667cdb-0792-4fa6-8945-4a41ae6118f3.png)

Im using Velocity build #156

**Comment by 4drian3d** [comment] 2022-06-22 13:52
Make sure you are connecting to Velocity and not to an individual server, that motd is the default for Minecraft Vanilla, not Velocity.

Otherwise, check how you have configured the https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/resources/default-velocity.toml#L67 option and check what each alternative is for

**Comment by wiktor-jozwiak** [comment] 2022-06-22 13:55
@4drian3d  I'm sure I connect via velocity, after entering the server from this ip are all the commands velocity, etc, the problem is that when I turn off the lobby for example, MOTD Velocity for a moment changes to the MOTD of ordinary servers that are connected to Velocity.

**Comment by wiktor-jozwiak** [comment] 2022-06-22 13:56
It's my configuration:
![image](https://user-images.githubusercontent.com/61411400/175047092-6ca1fa97-761a-45c3-8b18-d8ed4e67ce32.png)

**Comment by 56738** [comment] 2022-06-22 16:10
Since 1.19 servers send their MOTD + icon to players after they connect. Velocity probably needs to remove those values from the [server data packet](https://wiki.vg/Protocol#Server_Data) to prevent this.

**Comment by wiktor-jozwiak** [comment] 2022-06-22 20:00
@56738 good, thanks very much for your answer

**Comment by astei** [comment] 2022-06-23 02:29
Oh, Mojang, why'd you have to do this? I'll get a PR up for this.

**Comment by astei** [comment] 2022-06-23 03:36
This will be resolved by #771

**Comment by astei** [comment] 2022-06-24 03:59
merged as 662fbc4e3cc1ebbd817af6bb01a12cc46f479c2a

**Closed as completed by astei** 2022-06-24 03:59 UTC

**Comment by Aurelien30000** [comment] 2022-06-26 08:41
Unsure if this is expected, but this doesn't seem to be fixed when a client if kicked out of the minecraft server and then gets disconnected from the proxy.
With a normal disconnection, proxy MOTD and favicon are shown, however, if caused by a server kick, server-specific MOTD and favicon are shown, even if modified listening to the ``ProxyPingEvent``. Note: other info like sample players are always correct (proxy side).
