### ISSUE TITLE
Changing dimension with 1.19 client using viaversion kicks player.

### ISSUE THREAD

**Issue by SirKillian** [PaperMC/Velocity#725] opened 2022-06-07 16:13 UTC
When using ViaVersion 4.3.0 on the proxy it will kick players instantly when they change dimension.

Error: https://paste.helpch.at/eyujebitoq.log

**Comment by LemonCaramel** [comment] 2022-06-07 16:14
velocity does not yet support 1.19

**Comment by SirKillian** [comment] 2022-06-07 16:14
Note from kenny: 
 "https://i.imgur.com/MIvmUNB.png shouldn't send mangled, randomly sorted dimension data with partially wrong data fields in DimensionData (and instead properly handle/passthrough the original nbt data)"

**Comment by Strahilchu** [comment] 2022-06-07 16:17
Can confirm, after you join back you will be in the next dimension though

**Comment by seb303** [comment] 2022-06-07 18:42
Regardless of whether Velocity supports 1.19 yet, it should still work with ViaVersion and 1.19 client.
The cause of the problem is apparently "Velocity completely scrambling the order and adding outdated/wrong fields"
See: https://github.com/ViaVersion/ViaVersion/issues/2915
Also: https://github.com/ViaVersion/ViaVersion/issues/2916

**Comment by Quantum64** [comment] 2022-06-07 18:44
In my opinion, the problem is Velocity adding additional fields. Velocity reordering the fields does not violate the specification.

**Comment by seb303** [comment] 2022-06-08 13:57
This appears to be fixed now with velocity-3.1.2-SNAPSHOT-147

**Comment by Higgins4k** [comment] 2022-06-08 17:46
Is there any 1.19 tracker to see when Velocity will support it?

**Comment by ixn075** [comment] 2022-06-08 17:48
> Is there any 1.19 tracker to see when Velocity will support it?

I guess, there's a build with 1.19 support already.

**Comment by 4drian3d** [comment] 2024-02-14 17:56
As already mentioned and as I just checked, this bug was already fixed 2 years ago

**Closed as completed by 4drian3d** 2024-02-14 17:56 UTC
Labels: type: bug
