### ISSUE TITLE
Not Ending Packets?

### ISSUE THREAD

**Issue by davidmayr** [PaperMC/Velocity#409] opened 2020-12-25 22:24 UTC
When I get kicked from a Fallback server and get "disconnected" I cannot reconnect again. I will get kicked for "You are already connected" forever. When joining another Minecraft Server things like the Actionbar are stil lfrom the old server.

For the Tablist it is the same. When the other Server also has a Tablist they will switch forever.
Is there some Connection that wont be canceled? I am on 1.16.4 btw.

**Comment by davidmayr** [comment] 2020-12-25 22:25
I also get these Action bar messages on SinglePlayer. I seem to get incomming Packets from the Network I joined(with Velocity) but there are no packets outgoing to it.

There should be none going in or out in this case

**Comment by astei** [comment] 2020-12-25 22:26
If there is a bug here, it is in vanilla, not Velocity. I've seen reports of this happening without Velocity being involved. Closing this issue since it's not a Velocity bug.

**Comment by astei** [comment] 2020-12-25 22:27
Easy fix for this is to restart your client and make sure firewalls and such are not mucking things up. There is nothing more we can do.

**Closed as completed by astei** 2020-12-25 22:26 UTC
Labels: out of scope

**Comment by davidmayr** [comment] 2020-12-25 22:30
I know I need to restart my Client but afaik in other Proxies this isn't a problem.

**Comment by davidmayr** [comment] 2020-12-25 22:33
I never experienced this in Bungeecord... But thanks for the help.

**Comment by astei** [comment] 2020-12-25 22:36
In any event I am not able to reproduce this. Without more information and possibly direct access to your setup I can't possibly look at this further.
