### ISSUE TITLE
sendMessage not respecting newline and escape characters properly.

### ISSUE THREAD

**Issue by AriDeve** [PaperMC/Velocity#562] opened 2021-08-19 11:53 UTC
When sending a message containing an escaped newline character (So `\\n`) Velocity will send `\` with new line instead of `\n` to chat.

**Comment by astei** [comment] 2021-08-19 18:50
That's because you're not sending the message correctly. Construct your components properly and use `Component.newline()` as necessary.

Closing as this is not a bug in Velocity.

**Closed as completed by astei** 2021-08-19 18:50 UTC
Labels: out of scope

**Comment by tomcraft** [comment] 2021-08-19 19:48
I don't think the Minecraft client support escaping characters. You could do the "trick" by sending the `\` and the `n` in two different components, maybe.

**Comment by AriDeve** [comment] 2021-08-19 20:11
> I don't think the Minecraft client support escaping characters. You could do the "trick" by sending the `\` and the `n` in two different components, maybe.

As far as I know, vanilla minecraft clients don't deal with \n at all, and would leave it be as a string. As for your suggestion, it could work, but it would be annoying to implement in my use case.

> That's because you're not sending the message correctly. Construct your components properly and use `Component.newline()` as necessary.
> 
> Closing as this is not a bug in Velocity.

But something on velocity side of things is parsing a component (GSON for example) that is this `{"text":"Test \\n message"}` (The \n is not a newline character yet, it's just 2 characters of a string), to have make a new line. My components are properly constructed.

**Comment by astei** [comment] 2021-08-19 22:12
> But something on velocity side of things is parsing a component (GSON for example) that is this `{"text":"Test \\n message"}` (The \n is not a newline character yet, it's just 2 characters of a string), to have make a new line. My components are properly constructed.

Velocity has nothing to do with this. All Velocity is doing is calling Adventure to serialize a component and sends it in a packet.
