### ISSUE TITLE
Latest Velocity builds break LoginListener

### ISSUE THREAD

**Issue by R00tB33rMan** [PaperMC/Velocity#1189] opened 2024-01-13 04:59 UTC
https://pastebin.com/bGkhpCRp

LoginListener appears to no longer function for LimboAPI + Leaf (Leaf under brand identification on login). Reattempted on build 316 without issues.

**Comment by Timongcraft** [comment] 2024-01-13 06:52
The plugin uses Velocity internals, which have changed here: https://github.com/PaperMC/Velocity/commit/08c03aaea2bf69673a739494e7d8884d31c5002d#diff-21bfe45fceef334ff31a560a61e5c9cf010bdd8f0f663d994335fd12f1029a57R158.
It only needs to be compiled against the new internals.
Plugins that use internals are not supported; therefore, this is not a Velocity issue.
Until the issue is fixed by the plugin author you should downgrade to build [#319](https://api.papermc.io/v2/projects/velocity/versions/3.3.0-SNAPSHOT/builds/319/downloads/velocity-3.3.0-SNAPSHOT-319.jar).

**Closed as not planned** 2024-01-13 07:06 UTC
