### ISSUE TITLE
Unable to connect to Forge-Spigot hybrid 1.16.5 server

### ISSUE THREAD

**Issue by Spreax** [PaperMC/Velocity#962] opened 2023-03-04 21:35 UTC
I'm trying to setup a Pixelmon server with Velocity but no matter what Kind of Forge-Spigot server I use, I always get the same error. "This server has mods that require Forge to be installed on the client. Contact your server admin for more details.". I see people all the time using Arclight with Veloctity for their 1.16.5 Pixelmon servers But it seems like I still get the same result with Velocity and Arclight. I am going to settle using this proxy and server hybrid as that's what other people are using and it works for them.

I am using Forge-1.16.5-36.2.39 on my Forge Arclight server

I don't think it has to do anything with plugins. but If you need my plugins list anyways I will provide an image of all plugins.

Yes I am submitting this issue here instead of the Arclight issues page because I get the same result with other hybrid servers such as Magma and even went as far as using Mohist.

I cant find answers anywhere else. Its either people saying that forge isn't supported when clearly it is with other Pixelmon servers or people just saying "Its fixed" without providing any other information of how they got it to work.

Thank you.

P.S I do have the exact Pixelmon Reforged version as the one in my server as well as the same forge version.

![image_2023-03-04_163510139](https://user-images.githubusercontent.com/106390400/222929638-ea0741fd-342c-4737-b79b-99774b88766f.png)

**Comment by electronicboy** [comment] 2023-03-04 21:40
Proxies basically do not work with forge, and this is unavoidable without wider changes in the community to support this
There are a few "solutions" out there such as the ambassador plugin, but, nothing is supported by forge or us at the moment

Closing as a duplicate of #248

**Closed as not planned by electronicboy** 2023-03-04 21:40 UTC

**Comment by Xernium** [comment] 2023-03-04 21:46
To add onto this:
We will never officially support forge + spigot hybrids of any kind. Even if they work they're a less stable combination of both platforms.
The only supported setups with forge and plugins are with sponge since sponge was actually designed with modded environments in mind.

**Comment by Teastrands** [comment] 2023-03-04 23:15
https://github.com/adde0109/Ambassador

**Comment by Teastrands** [comment] 2023-03-04 23:16
and https://github.com/adde0109/Proxy-Compatible-Forge
