### ISSUE TITLE
Sending a resource pack in configuration phase can brick the client

### ISSUE THREAD

**Issue by davidmayr** [PaperMC/Velocity#1164] opened 2023-12-21 20:37 UTC
In the way Minecraft 1.20.4 is designed, the server can send a resource pack in the configuration phase and end the configuration phase immediately after, without waiting for the resource pack to be applied on the client. This is not recommended of course but 100% possible with the vanilla client. 

But because of velocities async nature the resource pack event is fired asynchronously, and the packet gets sent to the client after the configuration phase has already ended in this case. This causes the client to disconnect with a huge stack trace because it received a packet with ID 0x07 (I think?) that in the configuration phase is the resource pack packet and in play is the block entity data packet...
Since the client is already in play at this point, it reads it as a block entity data packet.

**Comment by electronicboy** [comment] 2023-12-21 20:42
Generally, a whole bunch of logic relating to server switching and the configuration phases needs to be rewritten, this is generally a known issue but is sadly somewhat of a backburner thing

**Comment by Gerrygames** [comment] 2023-12-23 12:38
Might be fixed by https://github.com/PaperMC/Velocity/commit/9450e6600cd823f7cdb207fe0c6bfb392af3e862. That commit fixed that the resource pack response was sent to the backend server with a wrong packet id. This issues describes an invalid packet being sent to the client, but I don't think that this is accurate. Feedback would be appreciated.

**Comment by davidmayr** [comment] 2023-12-28 16:04
> Might be fixed by [9450e66](https://github.com/PaperMC/Velocity/commit/9450e6600cd823f7cdb207fe0c6bfb392af3e862). That commit fixed that the resource pack response was sent to the backend server with a wrong packet id. This issues describes an invalid packet being sent to the client, but I don't think that this is accurate. Feedback would be appreciated.

I haven't really looked that deep into it and just figured that an invalid packet must have been sent because the client threw an exception while deserializing the block entity data packet, which is (obviously) not a resource pack packet. But looking at the commit, this must have been the fix for the disconnect, yeah. I can't really test if it was fixed either because I changed how I sent the resource pack already and don't have time to check if it works now. 

But I originally mentioned that resource packs (when just being thrown at the client without awaiting a response) would be sent outside the config phase. This Issue would (probably) still persist after the mentioned commit because of velocities async nature. As far as I have understood (not tested that yet tho) one would need to resend the pack during the config phase in order to switch servers without reloading the pack. That would, however, not be possible if velocity sends the pack after the config phase (because it does not await the resource pack event to be processed and just sends the resource pack whenever the event is finished) has already ended. 

If I am understanding the change in 1.20.4 to keep the resourcepack incorrectly, that wouldn't be an issue. But if it really works like that, that should probably be fixed somehow

**Comment by electronicboy** [comment] 2024-02-06 11:36
I've finally figured out the cause for this; The issue here is that we short circuit to assume that if a pack has already been denied, we shouldn't pester the client again, which creates an issue as there is no response sent to the server, and so it waits in configuration mode waiting for a response before it allows the connection to continue. There are potentially other issues here, hopefully the refactor cleans some of them up

**Closed as completed** 2024-02-08 16:15 UTC
Labels: type: bug
