### ISSUE TITLE
Bukkit PlayerResourcePackStatusEvent doesn't work on Velocity

### ISSUE THREAD

**Issue by DaJokni** [PaperMC/Velocity#654] opened 2022-02-28 19:27 UTC
A "recent" commit seems to have broken the "PlayerResourcePackStatusEvent" in the bukkit api, it just doesnt fire ever. I'd assume that the packets related to accepting the resource packs arent being sent back to the backend.

The pack gets sent just fine to the client, but the backend server doesnt seem to get that info.

The same thing works just fine on the build (build 110) before that commit.

The commit in question: https://github.com/PaperMC/Velocity/commit/596d4758ba9efedc60ede2789644ea10263c48e4

EDIT: And no, errors don't show up, not in the backend or velocity.

**Comment by codeHusky** [comment] 2022-03-01 10:55
This is causing a critical issue with our custom gamemode server - no errors from what I can see either and we're on the latest dev build available tonight (build 115). Important this event works so we can kick players who don't accept the resource pack.

**Comment by DeprecatedLuke** [comment] 2022-03-01 13:11
Confirmed, having the same issue.

**Comment by ytnoos** [comment] 2022-03-02 12:50
Same issue

**Comment by CoreyShupe** [comment] 2022-03-02 14:40
I'll test this out and work on a fix on Saturday. If anyone finds anything before then feel free to PR and ref the issue.

If anyone wants to give it a crack, I think the issue lies in the changes to the `Origin` stuff for the resource packs. That's where I'd recommend looking at first for the control flow of status sends.

**Comment by electronicboy** [comment] 2022-03-02 14:42
Just to confirm, the pack is being sent from the backend server and not the proxy?

**Comment by DaJokni** [comment] 2022-03-02 14:44
> Just to confirm, the pack is being sent from the backend server and not the proxy?

That is indeed the case, with Player#setResourcePack

**Comment by CoreyShupe** [comment] 2022-03-02 15:25
https://github.com/PaperMC/Velocity/pull/659 Can you see if the issue still resides in this PR.

**Comment by codeHusky** [comment] 2022-03-03 02:15
can confirm the issue is fixed with #659, posted picture there

**Comment by CoreyShupe** [comment] 2022-03-03 10:10
Note: This should be closed, #659 merged

**Closed as completed** 2022-03-04 05:58 UTC

**Comment by OverBrave** [comment] 2022-06-09 21:11
I am still having this problem. Can you check again?

Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)
