### ISSUE TITLE
[Urgent] CommandExecuteEvent can no longer be cancelled!

### ISSUE THREAD

**Issue by SkyLicks** [PaperMC/Velocity#827] opened 2022-08-08 03:20 UTC
The CommandExecuteEvent can no longer be cancelled since I updated velocity to support 1.19.1.  ALL plugins cancelling the CommandExecuteEvent no longer work.

Here is some test code to try this with. You will observe that the event IS fired however, attempting to cancel the event has no effect.
`
@Subscribe (order = PostOrder.LATE)
    public void onCommand(CommandExecuteEvent event) {

        if (!(event.getCommandSource() instanceof Player)) return;
        Player player = (Player) event.getCommandSource();
        player.sendMessage(Component.text("Attempting to cancel this event!"));
        event.setResult(CommandExecuteEvent.CommandResult.denied());
    }
`

**Comment by astei** [comment] 2022-08-08 03:42
Unsurprisingly, this is because Mojang has made this much more difficult. #804 is the issue to track this. Closing as a duplicate.

**Comment by Aseeef** [comment] 2022-08-08 03:48
Chat messages can be cancelled but commands can't be cancelled? Are you sure this really is related to chat signing?

**Comment by SkyLicks** [comment] 2022-08-08 04:34
> @SkyLicks You provided no other information other than "I updated to support 1.19.1 and now cancelling commands doesn't work". I made the very reasonable assumption that you're using 1.19.1 and expected the functionality to work, but it doesn't.

Apologies for the confusion. To clarify, all my backend servers are using 1.12.2. Most of my users also use 1.12.2 however, for the sake of support 1.19.1 users (via viaversion), I updated velocity. I am just making note of this fact in case this issue is seperate from the chat signing issues in #804.

Given no messages are being signed, I wouldn't expect there to be an issue with canceling commands (especially when regular messages are canceled just fine). Ofcourse I am not aware of the technical details of how velocity implemented chat signing so if this issue is indeed linked to #804, I will wait on a resolution for that issue. Otherwise, this issue should be reopened.

**Comment by astei** [comment] 2022-08-08 04:41
Thank you for providing clarification on this. I can confirm this is a real bug.

**Comment by astei** [comment] 2022-08-08 04:42
This should now be fixed

**Closed as completed by astei** 2022-08-08 04:42 UTC

**Comment by astei** [comment] 2022-08-08 04:46
Note that cancelling commands on >=1.19 still isn't supported due to the way the Minecraft chat signing scheme works right now with Velocity. #804 still tracks that issue.

**Comment by BBaoVanC** [comment] 2022-08-08 06:19
Does this apply to unsigned messages coming from <1.19?
