### ISSUE TITLE
Maybe a netty error (the proxy stop accepting connections)

### ISSUE THREAD

**Issue by Haykkonen** [PaperMC/Velocity#558] opened 2021-08-07 20:59 UTC
![image](https://user-images.githubusercontent.com/60020692/128613732-56000a5f-fcea-4b3a-a5f6-2aecc4370773.png)
![image](https://user-images.githubusercontent.com/60020692/128613720-6deafabb-b7c4-45e2-af43-c450472e416e.png)

Hi, hope we can find a fix for this ;)

About the error its caused by a well known attack on brazil, imo its a flood of bad logins/handshakes or just plain bot spam.
When the attack occurs the servers cpu goes up about 20-30% and the proxy stop accepting connections but the already established connections are maintaned with no harm.

I was having the same issue with waterfall and its forks, no luck on finding the fix for it tho.

Specs:
Centos 7, Kernel 5.13 with fs-filemax already increased to 65543

Velocity version: latest (dev)
Plugins installed: LuckPerms

jdk 11 installed

**Comment by astei** [comment] 2021-08-07 21:24
There is nothing we can really do on our end, you simply have too many connections open to your machine. Either add more machines to absorb the attack, implement rate-limiting before any connections make it to the proxy, or use a service to protect against the attacks.

Closing this issue as it is not actionable for us.

**Closed as completed by astei** 2021-08-07 21:24 UTC
Labels: out of scope

**Comment by astei** [comment] 2021-08-07 21:26
You can also try to raise your ulimit for open files. Fedora-like distributions tend to have low open file limits, so increasing the limit may help.

Aside from that, nothing much we can do.

**Comment by Haykkonen** [comment] 2021-08-07 21:40
Raising ulimit for open files didnt worked.. I still think is a netty related thing

saw this on a stackoverflow topic reporting the same issue ->

You should override exceptionCaught method in one of your handlers.

The message means that netty caugth exception but you didn't handle it in any of your handlers. Exceptions just reach the last pipeline handler and disappear. You probably should handle it in your request handler.

And close all streams after you finish working with files. And also you should release sockets and other resources on exceptions or unregistered events.

**Comment by aegontargaryen-dev** [comment] 2021-08-07 21:45
Having this same issue, i think its a netty related issue too.

**Comment by Leymooo** [comment] 2021-08-07 21:49
you can try to edit `/etc/security/limits.conf` https://stackoverflow.com/a/32699260 to increase open files limit.

also you can try to tweak some kernel settings https://javapipe.com/blog/iptables-ddos-protection/

**Comment by astei** [comment] 2021-08-07 22:01
> Having this same issue, i think its a netty related issue too.

> And close all streams after you finish working with files. And also you should release sockets and other resources on exceptions or unregistered events.

This is a resource exhaustion issue on your server, not a Velocity issue. We use static code analysis to catch basic bugs that can lead to resource exhaustion, and use well-established libraries with known-good resource cleanup, like log4j. Furthermore, we have safety guards to close connections proactively in the case that a connection should not be open but it still is. So this is a nothingburger.

> The message means that netty caugth exception but you didn't handle it in any of your handlers. Exceptions just reach the last pipeline handler and disappear. You probably should handle it in your request handler.

I don't even think you understood what the error message meant. It is a _bug_, but it is largely cosmetic in nature, so it is a very low priority to fix. There is in fact an `exceptionCaught` handler on every connection, but the problem is that the boss event loop cannot accept connections because you ran out of free file descriptors, _which is not our problem_.

In addition, given circumstantial evidence, your server appears to be running in offline mode, which is a configuration we do not support. I understand why this is a necessity given that Minecraft is relatively expensive in Brazil, but offline mode generally generates many more support issues for us and our bandwidth is limited.
