### ISSUE TITLE
Invalid Crash

### ISSUE THREAD

**Issue by TheWylot** [PaperMC/Velocity#951] opened 2023-02-19 12:01 UTC
My server randomly crashes on +250 Players, with a long error

exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@24607d
java.lang.IllegalStateException: Not connected to server!
	at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.ensureConnected(VelocityServerConnection.java:218) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.ChatQueue.queuePacket(ChatQueue.java:58) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.CommandHandler.queueCommandResult(CommandHandler.java:58) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.legacy.LegacyCommandHandler.handlePlayerCommandInternal(LegacyCommandHandler.java:45) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.legacy.LegacyCommandHandler.handlePlayerCommandInternal(LegacyCommandHandler.java:27) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.CommandHandler.handlePlayerCommand(CommandHandler.java:42) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:261) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.packet.chat.legacy.LegacyChat.handle(LegacyChat.java:121) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity-3.2.0-226.jar:3.2.0-SNAPSHOT (git-cd35e8f8-b226)]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheWylot** [comment] 2023-02-19 12:01
all of the players get read timed out after this error and the error just getting repeated with each player dc

**Comment by Xernium** [comment] 2023-02-19 15:10
Please list your plugins. This is most likely caused by a plugin holding a chat message indefinitely to cancel it, which is not supported and causes resource leaks

**Comment by TheWylot** [comment] 2023-02-19 19:26
> Please list your plugins. This is most likely caused by a plugin holding a chat message indefinitely to cancel it, which is not supported and causes resource leaks


[23:02:17 INFO]: Plugins: ajqueue, authmevelocity, bedwarscounter, dbconnector, discordjdavelocity, enhancedvelocity, litebans, luckperms, madantibot, sayanchat, serverlistplus, skinsrestorer, uarvp,
velocityreport, velocityvanish, vulcan

**Comment by TheWylot** [comment] 2023-02-21 21:42
@Xernium ^^

**Comment by Hackerjef** [comment] 2023-07-03 22:52
I've been getting this as well, After this error, Velocity Kinda just dies

From TheWylots plugin list we share Vulcan, litebans, luckperms. 

Our stackstrace:
java.lang.IllegalStateException: Not connected to server!
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.ensureConnected(VelocityServerConnection.java:218) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.ChatQueue.queuePacket(ChatQueue.java:58) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedChatHandler.handlePlayerChatInternal(KeyedChatHandler.java:93) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedChatHandler.handlePlayerChatInternal(KeyedChatHandler.java:33) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.ChatHandler.handlePlayerChat(ChatHandler.java:30) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:249) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedPlayerChat.handle(KeyedPlayerChat.java:152) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by 4drian3d** [comment] 2024-02-14 14:45
Fixed in https://github.com/PaperMC/Velocity/commit/f6fbd258052200172ccd39854c5330dd36717db2

**Closed as completed by 4drian3d** 2024-02-14 14:45 UTC
Labels: type: bug
