### ISSUE TITLE
listen for haproxy on different port

### ISSUE THREAD

**Issue by shithubsucks** [PaperMC/Velocity#1282] opened 2024-04-02 11:51 UTC
Currently I have noticed that if you enable listening for haproxy protocol in the settings it disables the ability for clients to connect natively without haproxy. This is undesired as haproxy is only being used for IPv6 transition purposes where IPv6 clients can directly connect to the server but IPv4 clients are relayed through Haproxy and converted to IPv6 internally.

It would be much better if Velocity could listen for haproxy on a different port while at the same time still listening for native clients on the normal port.

**Comment by clrxbl** [comment] 2024-04-02 11:58
This realistically should be https://github.com/PaperMC/Velocity/issues/1046
An alternative workaround for now would be to host a secondary Velocity instance with HAProxy enabled.

**Comment by shithubsucks** [comment] 2024-04-02 21:44
I feel like the scope on #1046 is a bit different but thank you for the workaround suggestion. That should work in the meantime but is massively inefficent. There is some crossover however, as I believe the issue in #1046 could possibly be addresses with the addition of haproxy and it's ability to arbitrarily bind to anything it's host can. The primary purpose of this is to preserve the source ip address to the application servers.

**Comment by shithubsucks** [comment] 2024-04-02 22:36
The workaround of running a second velocity daemon seemed to have worked. I appreciate it. This is hardly ideal though.

**Comment by electronicboy** [comment] 2024-04-03 07:16
The scope is the exact same, just with the caveat that you also want haproxy to be configurable per listener; closing as a duplicate of #1046

**Closed as not planned by electronicboy** 2024-04-03 07:16 UTC
