### ISSUE TITLE
HEX && RGB Support

### ISSUE THREAD

**Issue by ElinCode** [PaperMC/Velocity#976] opened 2023-03-15 08:16 UTC
messages.properties NOT RGB SUPPORT FIX

**Comment by ElinCode** [comment] 2023-03-15 08:17
If you can't fix it in messages.properties then make a .yml file

**Comment by Xernium** [comment] 2023-03-15 11:20
This is known, the message property file will support the MiniMessage format in the future but not the problematic Bungeecord hex color format

**Comment by 4drian3d** [comment] 2023-03-15 14:28
> If you can't fix it in messages.properties then make a .yml file

I was working on it in the pull requests https://github.com/PaperMC/Velocity/pull/721 and https://github.com/PaperMC/Velocity/pull/718 . But yesterday Adventure released its version 4.13.0 that implements https://github.com/KyoriPowered/adventure/pull/871 but in order to use it in Velocity,  it is necessary to create an own TranslationRegistry system or implement support for a "postprocessor" type for the TranslationRegistryImpl of Adventure itself.

And it has nothing to do with the properties format instead of yaml, personally I avoid using yaml as well😅

**Comment by ElinCode** [comment] 2023-03-16 06:39
А поддержка когда будет приблизительно? Мини Меседж с поддержкой HEX?

**Comment by ElinCode** [comment] 2023-03-16 06:39
When will support be available? Mini Message with HEX support?

**Comment by electronicboy** [comment] 2023-03-16 14:17
There is no eta, in the meantime, you can use a plugin, like minimotd

**Comment by 4drian3d** [comment] 2023-03-16 14:34
> There is no eta, in the meantime, you can use a plugin, like minimotd

This issue is about MiniMessage support in Velocity translations.
For the motd issue, yesterday PaperMC/Velocity#666 was merged which adds MiniMessage support to the motd configuration option

**Comment by 4drian3d** [comment] 2023-03-16 14:39
Also, this issue is duplicate of #720

**Comment by electronicboy** [comment] 2023-03-16 14:40
oh, derp;

Well, duplicate of #720

**Closed as not planned by electronicboy** 2023-03-16 14:40 UTC
Labels: resolution: duplicate

**Comment by ElinCode** [comment] 2023-03-18 06:30
> Also, this issue is duplicate of #720


I don't need HEX in the mod, but in messages.properties

**Comment by 4drian3d** [comment] 2023-03-18 19:59
> > Also, this issue is duplicate of #720
> 
> I don't need HEX in the mod, but in messages.properties

That is why this issue is duplicated

**Comment by BrIruka** [comment] 2025-05-12 19:15
https://github.com/BrIruka/VelocityHEXMsg
