### ISSUE TITLE
Allow multiple forwarding modes

### ISSUE THREAD

**Issue by caunt** [PaperMC/Velocity#1145] opened 2023-11-23 15:27 UTC
As title says, looking for a way to support multiple forwarding modes in same time for different registered servers. I'd like to setup one backend server as legacy (< 1.13), and one as modern. It would be difficult to configure this such a setup in config file, but it would allow for plugins to register servers with customizable forwarding mode.

The problem is I want to support 1.7.10 to newest versions of the game, but PlayerInfoForwarding is tied to configuration file.

Solution: save forwarding mode for each server probably and register servers like this
```
ProxyServer.registerServer(new ServerInfo("legacy_lobby", ..., PlayerInfoForwarding.LEGACY))
ProxyServer.registerServer(new ServerInfo("modern_lobby", ..., PlayerInfoForwarding.MODERN))
```

**Comment by powercasgamer** [comment] 2023-11-23 16:28
duplicate of #566

**Comment by caunt** [comment] 2023-11-24 10:34
It's open for over 2 years already 🫠 all needed to solve this problem is just save PlayerInfoForwarding mode into server instance.

It is not necessary to rearchitecture whole backend to solve this simple problem

**Comment by electronicboy** [comment] 2023-11-24 12:47
The existing configuration setup doesn't support this, and, generally, PRs welcome

**Closed as not planned by electronicboy** 2023-11-24 12:47 UTC
