### ISSUE TITLE
Hybrid Forwarding(Use different types of forwarding on different servers)

### ISSUE THREAD

**Issue by kalebchoi** [PaperMC/Velocity#584] opened 2021-10-10 08:24 UTC
I think it would be nice to have the ability to use multiple methods of forwarding to servers. So you could have a situation where you have modern forwarding on newer versions, bungeeguard for 1.8, etc. So the Network could be secure as possible for the various different versions and backends someone may want to run.

**Comment by astei** [comment] 2021-10-10 08:28
Duplicate of #304

**Closed as completed by astei** 2021-10-10 08:28 UTC
