### ISSUE TITLE
Feature request: Plugins update folder

### ISSUE THREAD

**Issue by maxcom1** [PaperMC/Velocity#1258] opened 2024-02-27 18:22 UTC
Hey!
On paper, we have something like the `plugins/update` folder. On the server start, the plugins in the `plugins` folder are replaced by those we put in the update folder. Updater checks these jars against the names in plugin.yml and matches them to the names in the main plugins folder, so they don't have to have the same __file__ name.

**Why should this be implemented to Velocity?**
As we know, we should not touch plugin jar files when the server is running. So if we want to update any plugin, the only option is to turn off the whole proxy (which kicks players from the server), delete the old jar file, upload the new one and turn the server back on. Realistically this is very difficult. It should happen automatically

**Comment by 4drian3d** [comment] 2024-02-27 18:24
Duplicate of #809

**Closed as not planned by 4drian3d** 2024-02-27 18:24 UTC
Labels: resolution: duplicate
