### ISSUE TITLE
Command Tab Completion

### ISSUE THREAD

**Issue by SkyLicks** [PaperMC/Velocity#615] opened 2021-12-19 18:11 UTC
I have a "special" setup using RedisBungee with Velocity. My issue is that the plugin I am using does not do TabCompletions across my RedisBungee Instances.

This was fine when I used Bungee because I could use BungeeCord's TabCompleteEvent to accommodate for this. However, Velocity's TabCompleteEvent only works for messages without a "/".

I see that in previous tickets on this issue, you guys said this was intentional. However, how do I then circumnavigate this issue and offer tab completions for my ban commands? Is there a certain packet listener I can use? There is very little documentation on PacketListeners for velocity (though I rather avoid packet listeners).

**Comment by hugmanrique** [comment] 2021-12-20 00:14
All command implementations have one way or another to provide suggestions to clients. For commands implementing `InvocableCommand` (e.g. `SimpleCommand`), use [`suggest`](https://jd.velocitypowered.com/3.0.0/com/velocitypowered/api/command/InvocableCommand.html#suggest(I)); for Brigadier commands, add the desired `SuggestionProvider`.

Note that `TabCompleteEvent` no longer fires for 1.13+ clients and is _not_ intended to be used for command suggestions.

**Comment by astei** [comment] 2021-12-26 23:26
Closing this because the API is working as designed. We moved tab completion into commands because it is how Mojang intended command tab complete to be handled in Minecraft 1.13 and above.

**Closed as completed by astei** 2021-12-26 23:26 UTC
