### ISSUE TITLE
HEX on messages.properties

### ISSUE THREAD

**Issue by DarkKeeper1** [PaperMC/Velocity#838] opened 2022-08-15 04:07 UTC
Faced a problem that I can't make HEX in Velocity translation messages (lang folder) please add this feature.

**Comment by 4drian3d** [comment] 2022-08-15 04:15
#721

**Comment by DarkKeeper1** [comment] 2022-08-15 04:49
> #721

And how to fix the problem?

**Comment by electronicboy** [comment] 2024-01-16 14:41
Duplicate of #720

**Closed as not planned by electronicboy** 2024-01-16 14:41 UTC
Labels: resolution: duplicate, type: feature
